# Generated by Django 4.1.3 on 2022-11-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_competitor_level"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Car",
        ),
    ]
